# Generated by Django 6.1 on 2026-09-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Навазние')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товыары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='group_name',
            field=models.TextField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.showcase'),
        ),
    ]
