# Generated by Django 6.1 on 2026-09-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_showcase_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Showcase',
            new_name='Type',
        ),
    ]
