# Generated by Django 6.1 on 2026-09-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_showcase_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='group_name',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.producttype', verbose_name='Категория'),
        ),
    ]
