# Generated by Django 6.1 on 2026-09-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_type_producttype_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
